name:                lambda-board
version:             0.1.0.0
github:              "githubuser/lambda-board"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lambda-board#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - karver
  - mtl
  - optparse-applicative
  - servant
  - servant-server
  - sqlite-simple
  - tasty >= 0.7
  - tasty-quickcheck
  - tasty-hunit
  - tasty-smallcheck
  - text
  - unordered-containers
  - vector
  - wai
  - warp

library:
  source-dirs: src
  default-extensions:
    - BlockArguments
    - DataKinds
    - DeriveGeneric
    - FlexibleContexts
    - FlexibleInstances
    - LambdaCase
    - MultiParamTypeClasses
    - OverloadedStrings
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - UndecidableInstances

executables:
  lambda-board-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-board

tests:
  lambda-board-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-board
