on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check Dockerhub credentials
        run: |
          set -x
          test -n "${{ secrets.DOCKERHUB_ORG }}"
          test -n "${{ secrets.DOCKERHUB_USERNAME }}"
          test -n "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Build and push Iroha Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_ORG }}/board
          tags: latest
